In [ ]:
import pandas as pd

In [3]:
file_path = 'D:/Colaberry/KMIT/Week_06/snowflake-financial-data-lakehouse/snowflake-financial-data-lakehouse/data/PS_20174392719_1491204439457_log.csv'

sample_data = pd.read_csv(file_path,nrows=1000)

In [6]:
for col in sample_data.columns:
    print(col)

step
type
amount
nameOrig
oldbalanceOrg
newbalanceOrig
nameDest
oldbalanceDest
newbalanceDest
isFraud
isFlaggedFraud

In [14]:
sample_data.head(20)

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.00,160296.36,M1979787155,0.0,0.00,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.00,19384.72,M2044282225,0.0,0.00,0,0
2,1,TRANSFER,181.00,C1305486145,181.00,0.00,C553264065,0.0,0.00,1,0
3,1,CASH_OUT,181.00,C840083671,181.00,0.00,C38997010,21182.0,0.00,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.00,29885.86,M1230701703,0.0,0.00,0,0
5,1,PAYMENT,7817.71,C90045638,53860.00,46042.29,M573487274,0.0,0.00,0,0
6,1,PAYMENT,7107.77,C154988899,183195.00,176087.23,M408069119,0.0,0.00,0,0
7,1,PAYMENT,7861.64,C1912850431,176087.23,168225.59,M633326333,0.0,0.00,0,0
8,1,PAYMENT,4024.36,C1265012928,2671.00,0.00,M1176932104,0.0,0.00,0,0
9,1,DEBIT,5337.77,C712410124,41720.00,36382.23,C195600860,41898.0,40348.79,0,0
10,1,DEBIT,9644.94,C1900366749,4465.00,0.00,C997608398,10845.0,157982.12,0,0
11,1,PAYMENT,3099.97,C249177573,20771.00,17671.03,M2096539129,0.0,0.00,0,0
12,1,PAYMENT,2560.74,C1648232591,5070.00,2509.26,M972865270,0.0,0.00,0,0
13,1,PAYMENT,11633.76,C1716932897,10127.00,0.00,M801569151,0.0,0.00,0,0
14,1,PAYMENT,4098.78,C1026483832,503264.00,499165.22,M1635378213,0.0,0.00,0,0
15,1,CASH_OUT,229133.94,C905080434,15325.00,0.00,C476402209,5083.0,51513.44,0,0
16,1,PAYMENT,1563.82,C761750706,450.00,0.00,M1731217984,0.0,0.00,0,0
17,1,PAYMENT,1157.86,C1237762639,21156.00,19998.14,M1877062907,0.0,0.00,0,0
18,1,PAYMENT,671.64,C2033524545,15123.00,14451.36,M473053293,0.0,0.00,0,0
19,1,TRANSFER,215310.30,C1670993182,705.00,0.00,C1100439041,22425.0,0.00,0,0

In [10]:
sample_data.dtypes

step                int64
type               object
amount            float64
nameOrig           object
oldbalanceOrg     float64
newbalanceOrig    float64
nameDest           object
oldbalanceDest    float64
newbalanceDest    float64
isFraud             int64
isFlaggedFraud      int64
dtype: object

In [13]:
sample_data['isFraud'].value_counts()

isFraud
0    991
1      9
Name: count, dtype: int64

In [15]:
sample_data['nameDest'].str.startswith('M').value_counts()

nameDest
False    563
True     437
Name: count, dtype: int64

In [19]:
pd.set_option('display.float_format', '{:.2f}'.format)

In [21]:
sample_data.describe(include='all')

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
count,1000.00,1000,1000.00,1000,1000.00,1000.00,1000,1000.00,1000.00,1000.00,1000.00
unique,NaN,5,NaN,1000,NaN,NaN,597,NaN,NaN,NaN,NaN
top,NaN,PAYMENT,NaN,C49318987,NaN,NaN,C1590550415,NaN,NaN,NaN,NaN
freq,NaN,437,NaN,1,NaN,NaN,23,NaN,NaN,NaN,NaN
mean,1.00,NaN,118199.53,NaN,864604.29,884998.83,NaN,665714.09,1224671.63,0.01,0.00
std,0.00,NaN,248479.89,NaN,2078040.48,2127790.41,NaN,2060515.15,3436780.05,0.09,0.00
min,1.00,NaN,8.73,NaN,0.00,0.00,NaN,0.00,0.00,0.00,0.00
25%,1.00,NaN,4474.73,NaN,0.00,0.00,NaN,0.00,0.00,0.00,0.00
50%,1.00,NaN,14658.08,NaN,14518.00,5661.83,NaN,28755.06,0.00,0.00,0.00
75%,1.00,NaN,142720.32,NaN,107909.25,102104.23,NaN,436631.17,730111.20,0.00,0.00
max,1.00,NaN,2545478.01,NaN,9716462.14,9987286.56,NaN,17664818.40,19169204.93,1.00,0.00

In [22]:
paysim_data = pd.read_csv(file_path)

In [31]:
paysim_data.shape[0]

6362620

In [26]:
paysim_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype
---  ------          -----
 0   step            int64
 1   type            object
 2   amount          float64
 3   nameOrig        object
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        object
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64
 10  isFlaggedFraud  int64
dtypes: float64(5), int64(3), object(3)
memory usage: 534.0+ MB

In [82]:
paysim_data.isna().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [84]:
paysim_data.duplicated().sum()

np.int64(0)

In [ ]:
paysim_data['step'].value_counts().sort_index()

step
1      2708
2      1014
3       552
4       565
5       665
       ...
739      10
740       6
741      22
742      14
743       8
Name: count, Length: 743, dtype: int64

In [32]:
paysim_data['step'].nunique()

743

In [30]:
paysim_data.describe(include='all')

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
count,6362620.00,6362620,6362620.00,6362620,6362620.00,6362620.00,6362620,6362620.00,6362620.00,6362620.00,6362620.00
unique,NaN,5,NaN,6353307,NaN,NaN,2722362,NaN,NaN,NaN,NaN
top,NaN,CASH_OUT,NaN,C1677795071,NaN,NaN,C1286084959,NaN,NaN,NaN,NaN
freq,NaN,2237500,NaN,3,NaN,NaN,113,NaN,NaN,NaN,NaN
mean,243.40,NaN,179861.90,NaN,833883.10,855113.67,NaN,1100701.67,1224996.40,0.00,0.00
std,142.33,NaN,603858.23,NaN,2888242.67,2924048.50,NaN,3399180.11,3674128.94,0.04,0.00
min,1.00,NaN,0.00,NaN,0.00,0.00,NaN,0.00,0.00,0.00,0.00
25%,156.00,NaN,13389.57,NaN,0.00,0.00,NaN,0.00,0.00,0.00,0.00
50%,239.00,NaN,74871.94,NaN,14208.00,0.00,NaN,132705.66,214661.44,0.00,0.00
75%,335.00,NaN,208721.48,NaN,107315.18,144258.41,NaN,943036.71,1111909.25,0.00,0.00
max,743.00,NaN,92445516.64,NaN,59585040.37,49585040.37,NaN,356015889.35,356179278.92,1.00,1.00

In [ ]:
from pathlib import Path

output_dir = Path('D:/Colaberry/KMIT/Week_06/snowflake-financial-data-lakehouse/snowflake-financial-data-lakehouse/batches')
output_dir.mkdir(exist_ok=True)

min_range = paysim_data['step'].min()
max_range = paysim_data['step'].max()
step_ranges = []
for start in range(min_range,max_range,100):
    if start==301:
        end = max_range
        step_ranges.append([start,end])
        break
    else:
        end = min(start+99,max_range)
        step_ranges.append([start,end])

for i,batch in enumerate(step_ranges,start=1):
    filename = f"batch_{i:03d}.csv"
    start = batch[0]
    end = batch[1]
    data = paysim_data[(paysim_data['step']>=start) & (paysim_data['step']<=end)]
    data.to_csv(output_dir/filename,index=False)

D:\Colaberry\KMIT\Week_06\snowflake-financial-data-lakehouse\snowflake-financial-data-lakehouse\batches

In [ ]:
batch_1=pd.read_csv('D:/Colaberry/KMIT/Week_06/snowflake-financial-data-lakehouse/snowflake-financial-data-lakehouse/batches/batch_001.csv')
print(batch_1.shape)
batch_2=pd.read_csv('D:/Colaberry/KMIT/Week_06/snowflake-financial-data-lakehouse/snowflake-financial-data-lakehouse/batches/batch_002.csv')
print(batch_2.shape)
batch_3=pd.read_csv('D:/Colaberry/KMIT/Week_06/snowflake-financial-data-lakehouse/snowflake-financial-data-lakehouse/batches/batch_003.csv')
print(batch_3.shape)
batch_4=pd.read_csv('D:/Colaberry/KMIT/Week_06/snowflake-financial-data-lakehouse/snowflake-financial-data-lakehouse/batches/batch_004.csv')
print(batch_4.shape)

(1059516, 11)